package review

import (
	"context"
	"reflect"
	"strings"
	"testing"
)

// section is one file's part of a diff for these tests: a header and one
// hunk with the lines given, "+" and "-" ones counted by the code under
// test.
func section(oldPath, newPath string, lines ...string) string {
	name := newPath
	if name == "" {
		name = oldPath
	}
	var out strings.Builder
	out.WriteString("diff --git a/" + name + " b/" + name + "\n")
	switch {
	case oldPath == "":
		out.WriteString("new file mode 100644\n--- /dev/null\n+++ b/" + newPath + "\n")
	case newPath == "":
		out.WriteString("deleted file mode 100644\n--- a/" + oldPath + "\n+++ /dev/null\n")
	default:
		out.WriteString("--- a/" + oldPath + "\n+++ b/" + newPath + "\n")
	}
	out.WriteString("@@ -1,2 +1,2 @@\n")
	for _, l := range lines {
		out.WriteString(l + "\n")
	}
	return out.String()
}

const generatedLine = "// Code generated by protoc-gen-go. DO NOT EDIT."

func TestSplitDiffNamesEachFileAndCountsItsLines(t *testing.T) {
	diff := section("widget.go", "widget.go", " package widget", "-func Old() {}", "+func New() {}", "+func Newer() {}") +
		section("", "added.go", "+package added") +
		section("gone.go", "", "-"+generatedLine, "-package gone") +
		"diff --git a/old name.go b/new name.go\nsimilarity index 100%\nrename from old name.go\nrename to new name.go\n" +
		"diff --git a/img.png b/img.png\nBinary files a/img.png and b/img.png differ\n"
	got := splitDiff(diff)
	type want struct {
		oldPath, newPath string
		added, removed   int
	}
	wants := []want{
		{"widget.go", "widget.go", 2, 1},
		{"", "added.go", 1, 0},
		{"gone.go", "", 0, 2},
		{"old name.go", "new name.go", 0, 0},
		{"img.png", "img.png", 0, 0},
	}
	if len(got) != len(wants) {
		t.Fatalf("%d sections, want %d: %+v", len(got), len(wants), got)
	}
	for i, w := range wants {
		s := got[i]
		if s.oldPath != w.oldPath || s.newPath != w.newPath || s.added != w.added || s.removed != w.removed {
			t.Errorf("section %d = %q -> %q +%d -%d, want %q -> %q +%d -%d", i, s.oldPath, s.newPath, s.added, s.removed, w.oldPath, w.newPath, w.added, w.removed)
		}
	}
	if got[2].removedLines[0] != generatedLine {
		t.Errorf("a deleted file's removed lines %q, want its old head", got[2].removedLines)
	}
	if joined := got[0].text + got[1].text + got[2].text + got[3].text + got[4].text; joined != diff {
		t.Errorf("the sections do not add up to the diff:\n%s", joined)
	}
}

func TestMatchGenerated(t *testing.T) {
	cases := []struct {
		pattern, path string
		match         bool
	}{
		{"*.pb.go", "api/v1/widget.pb.go", true},
		{"*.pb.go", "api/v1/widget.go", false},
		{"vendor", "vendor/acme/lib.go", true},
		{"vendor/", "vendor/acme/lib.go", true},
		{"vendor/*", "vendor/acme/lib.go", true},
		{"vendor/*.go", "vendor/acme/lib.go", false},
		{"gen/**/*.ts", "gen/a/b/c.ts", true},
		{"gen/**/*.ts", "gen/c.ts", true},
		{"gen/**/*.ts", "src/gen/c.ts", false},
		{"docs/api.md", "docs/api.md", true},
		{"docs/api.md", "docs/api.md.bak", false},
		{"./docs/api.md", "./docs/api.md", true},
		{"", "anything.go", false},
	}
	for _, c := range cases {
		got := matchGenerated([]string{c.pattern}, c.path)
		if (got != "") != c.match {
			t.Errorf("matchGenerated(%q, %q) = %q, want match %v", c.pattern, c.path, got, c.match)
		}
	}
}

// checkoutWithGenerated is a checkout of a pull request's head: a hand
// file, a file with the generated header, one .gitattributes marks, one
// it unmarks, and one a pattern names, with CheckoutBaseRef set so the
// diff can be read from it too.
func checkoutWithGenerated(t *testing.T) string {
	t.Helper()
	dir := gitRepo(t, "")
	commitFile(t, dir, "base.txt", "base\n")
	runGit(t, dir, "update-ref", CheckoutBaseRef, "HEAD")
	commitFile(t, dir, ".gitattributes", "marked.go linguist-generated\nalso.go linguist-generated=true\nunmarked.go -linguist-generated\n")
	commitFile(t, dir, "widget.go", "package widget\n\nfunc Widget() {}\n")
	commitFile(t, dir, "widget.pb.go", "// Copyright\n\n"+generatedLine+"\n\npackage widget\n")
	commitFile(t, dir, "marked.go", "package widget\n")
	commitFile(t, dir, "also.go", "package widget\n")
	commitFile(t, dir, "unmarked.go", "package widget\n")
	commitFile(t, dir, "schema.sql", "create table widget();\n")
	return dir
}

func TestExcludeGeneratedTellsGeneratedFilesFromHandFilesInACheckout(t *testing.T) {
	dir := checkoutWithGenerated(t)
	diff := section("widget.go", "widget.go", "-func Old() {}", "+func Widget() {}") +
		section("", "widget.pb.go", "+// Copyright", "+", "+"+generatedLine, "+package widget") +
		section("", "marked.go", "+package widget") +
		section("", "also.go", "+package widget") +
		section("", "unmarked.go", "+package widget") +
		section("gone.pb.go", "", "-"+generatedLine, "-package gone", "-func Gone() {}") +
		section("", "schema.sql", "+create table widget();")
	filtered, excluded, partial := excludeGenerated(context.Background(), diff, dir, []string{"*.sql"})
	if partial != "" {
		t.Errorf("partial = %q, want a complete detection with a checkout", partial)
	}
	want := []ExcludedFile{
		{Path: "widget.pb.go", Added: 4, Reason: ReasonHeader},
		{Path: "marked.go", Added: 1, Reason: ReasonAttribute},
		{Path: "also.go", Added: 1, Reason: ReasonAttribute},
		{Path: "gone.pb.go", Removed: 3, Reason: ReasonHeader},
		{Path: "schema.sql", Added: 1, Reason: ReasonPattern + ": *.sql"},
	}
	if !reflect.DeepEqual(excluded, want) {
		t.Errorf("excluded %+v\nwant %+v", excluded, want)
	}
	if wantDiff := section("widget.go", "widget.go", "-func Old() {}", "+func Widget() {}") + section("", "unmarked.go", "+package widget"); filtered != wantDiff {
		t.Errorf("filtered diff:\n%s\nwant the hand files alone:\n%s", filtered, wantDiff)
	}
}

func TestWithoutACheckoutOnlyThePatternsAreCheckedAndTheReviewSaysSo(t *testing.T) {
	diff := section("widget.go", "widget.go", "+func Widget() {}") +
		section("", "widget.pb.go", "+"+generatedLine, "+package widget") +
		section("", "schema.sql", "+create table widget();")
	filtered, excluded, partial := excludeGenerated(context.Background(), diff, "", []string{"*.sql"})
	if !strings.Contains(partial, "no checkout") || !strings.Contains(partial, ".gitattributes") {
		t.Errorf("partial = %q, want the checks that were skipped named", partial)
	}
	if len(excluded) != 1 || excluded[0].Path != "schema.sql" {
		t.Errorf("excluded %+v, want the pattern's file alone", excluded)
	}
	if !strings.Contains(filtered, "widget.pb.go") || strings.Contains(filtered, "schema.sql") {
		t.Errorf("filtered diff:\n%s", filtered)
	}
	// A checkout that is not a git repository costs the attributes check,
	// not the review, and the header check still runs.
	filtered, excluded, partial = excludeGenerated(context.Background(), diff, t.TempDir(), nil)
	if !strings.Contains(partial, ".gitattributes of the checkout could not be read") {
		t.Errorf("partial = %q, want the attributes read failure", partial)
	}
	if len(excluded) != 0 || !strings.Contains(filtered, "schema.sql") {
		t.Errorf("excluded %+v with no checkout files to read", excluded)
	}
}

func TestTheDiffSourceGathersTheDiffWithoutItsGeneratedFiles(t *testing.T) {
	f := sampleGH()
	f.diff = section("widget.go", "widget.go", "+func Widget() {}") + section("", "widget.pb.go", "+"+generatedLine, "+package widget")
	p, err := ParseProject("generated = [\"*.pb.go\"]\n", "/tmp/context.toml")
	if err != nil {
		t.Fatal(err)
	}
	bundle := gatherTest(t, f, p, "")
	items := bundle.Of(SourceDiff)
	if len(items) != 1 || strings.Contains(items[0].Content, "widget.pb.go") || !strings.Contains(items[0].Content, "widget.go") {
		t.Fatalf("diff items %+v, want the hand file alone", items)
	}
	want := []ExcludedFile{{Path: "widget.pb.go", Added: 2, Reason: ReasonPattern + ": *.pb.go"}}
	if !reflect.DeepEqual(bundle.Excluded, want) {
		t.Errorf("bundle.Excluded %+v, want %+v", bundle.Excluded, want)
	}
	if !strings.Contains(strings.Join(bundle.Skipped, "\n"), "generated files: no checkout") {
		t.Errorf("skipped %v, want the partial detection reported", bundle.Skipped)
	}
	if text := bundle.Text(); !strings.Contains(text, "## Generated files not reviewed\n") || !strings.Contains(text, "- widget.pb.go (+2 -0; generated in context.toml: *.pb.go)\n") {
		t.Errorf("bundle text does not list the excluded file:\n%s", text)
	}
	// The distiller carries the list into the brief, where the angles read
	// it, and a brief written before the field existed reads back with none.
	brief, err := (&Distiller{Agent: &fakeAgent{answer: answeredBrief}, Dir: t.TempDir()}).Distill(context.Background(), bundle)
	if err != nil {
		t.Fatal(err)
	}
	if !reflect.DeepEqual(brief.Excluded, want) {
		t.Errorf("brief.Excluded %+v, want %+v", brief.Excluded, want)
	}
	if text := brief.Text(); !strings.Contains(text, "## Generated files not reviewed\n") || !strings.Contains(text, "- widget.pb.go (+2 -0; generated in context.toml: *.pb.go)\n") {
		t.Errorf("brief text does not list the excluded file:\n%s", text)
	}
}

func TestADiffOfGeneratedFilesAloneIsEmpty(t *testing.T) {
	f := sampleGH()
	f.diff = section("", "widget.pb.go", "+"+generatedLine, "+package widget")
	p, err := ParseProject("generated = [\"*.pb.go\"]\n", "/tmp/context.toml")
	if err != nil {
		t.Fatal(err)
	}
	bundle := gatherTest(t, f, p, "")
	if items := bundle.Of(SourceDiff); len(items) != 0 {
		t.Fatalf("diff items %+v, want none", items)
	}
	if !strings.Contains(strings.Join(bundle.Skipped, "\n"), "the diff of acme/widgets#7 has nothing left once its generated files are taken out") {
		t.Errorf("skipped %v, want the diff reported as all generated", bundle.Skipped)
	}
	if len(bundle.Excluded) != 1 {
		t.Errorf("excluded %+v", bundle.Excluded)
	}
}

func TestGeneratedPatternsAreValidated(t *testing.T) {
	p, err := ParseProject("generated = [\"*.pb.go\", \"vendor/**\"]\n", "/tmp/context.toml")
	if err != nil {
		t.Fatal(err)
	}
	if !reflect.DeepEqual(p.Generated, []string{"*.pb.go", "vendor/**"}) {
		t.Errorf("generated = %v", p.Generated)
	}
	_, err = ParseProject("generated = [\"\", \"/abs/*.go\", \"../*.go\", \"[\"]\n", "/tmp/context.toml")
	if err == nil {
		t.Fatal("bad patterns parsed")
	}
	for _, want := range []string{"generated[0] is empty", "generated[1] \"/abs/*.go\" must be relative", "generated[2] \"../*.go\" must stay inside", "generated[3] \"[\" is not a valid pattern"} {
		if !strings.Contains(err.Error(), want) {
			t.Errorf("error %q does not say %q", err, want)
		}
	}
	if _, err := ParseProject("generated = \"*.pb.go\"\n", "/tmp/context.toml"); err == nil {
		t.Error("a string where a list is wanted parsed")
	}
}

// A pull request touching a generated file and a hand file: the distiller
// and the angles see the hand file's diff alone, the brief names the
// generated file with its line counts, and a finding on it is dropped.
func TestARunReviewsTheHandFilesAndDropsFindingsOnTheGeneratedOnes(t *testing.T) {
	agent := &reviewAgent{answers: map[string]string{
		AngleGeneral: sessionAnswer(
			`{"category": "naming", "severity": "high", "file": "widget.pb.go", "lines": [2, 2], "side": "new", "title": "A name in the binding", "body": "generated"}`,
			`{"category": "naming", "severity": "medium", "file": "widget.go", "lines": [1, 1], "side": "new", "title": "Receiver names here are short", "body": "w"}`,
		),
	}}
	r, log := testRunner(t, agent, nil)
	// The machine's checkout is not the pull request's head, so the
	// generated file is told by a pattern; its header is checked from the
	// checkout the review makes, which this runner does not.
	writeFile(t, r.Pipeline.Dir, ProjectFile, "generated = [\"*.pb.go\"]\n[angles]\nquick_general = false\ndocs = false\nside_effects = false\n")
	project, err := LoadProject(FindProject(r.Pipeline.Dir))
	if err != nil {
		t.Fatal(err)
	}
	r.Pipeline.Project = project
	f := sampleGH()
	f.diff = section("widget.go", "widget.go", "+func Widget() {}") + section("", "widget.pb.go", "+"+generatedLine, "+package widget", "+var Generated = 1")
	r.Pipeline.Client = f.client(t)

	a, err := r.Run(context.Background(), Ref{Repo: testRepo, Number: 7})
	if err != nil {
		t.Fatal(err)
	}
	want := []ExcludedFile{{Path: "widget.pb.go", Added: 3, Reason: ReasonPattern + ": *.pb.go"}}
	if !reflect.DeepEqual(a.Brief.Excluded, want) {
		t.Errorf("brief.Excluded %+v, want %+v", a.Brief.Excluded, want)
	}
	if p := agent.reqs[DistillerName].Prompt; strings.Contains(p, "var Generated") || !strings.Contains(p, "+func Widget() {}") || !strings.Contains(p, "- widget.pb.go (+3 -0; generated in context.toml: *.pb.go)") {
		t.Errorf("the distiller was given the generated file's diff, or not told of it:\n%s", p)
	}
	if p := agent.reqs[AngleGeneral].Prompt; !strings.Contains(p, "## Generated files not reviewed\n") || !strings.Contains(p, "- widget.pb.go (+3 -0; generated in context.toml: *.pb.go)") {
		t.Errorf("the angle was not told of the generated file:\n%s", p)
	}
	if got := titles(a.Findings.Items); !reflect.DeepEqual(got, []string{"Widget has no test", "Receiver names here are short"}) {
		t.Errorf("findings %v, want the finding on the generated file dropped", got)
	}
	if !strings.Contains(log.String(), "  1 finding on generated files dropped\n") {
		t.Errorf("log:\n%s", log.String())
	}
	// Without the pull request's checkout, the brief says the detection
	// was partial.
	if !strings.Contains(strings.Join(a.Brief.NotGathered, "\n"), "generated files: no checkout") {
		t.Errorf("not gathered %v, want the partial detection", a.Brief.NotGathered)
	}
}

// A reopened angle session may report a generated file too; what the
// review dropped, an ask drops as well.
func TestAnAskDropsAFindingOnAGeneratedFile(t *testing.T) {
	a := judged(t)
	a.Brief.Excluded = []ExcludedFile{{Path: "widget.pb.go", Added: 3}}
	onGenerated := `{"category": "naming", "severity": "high", "file": "widget.pb.go", "lines": [2, 2], "side": "new", "title": "A name in the binding", "body": "generated"}`
	answer := "Two more.\n\n```json\n" + sessionAnswer(onGenerated, rawFromAsk) + "\n```\n"
	q := askingQueue(t, a, &fakeAgent{answer: answer, id: "sess-tests"})
	got, err := q.Ask(context.Background(), a.Findings.Items[0].ID, "Anything else?")
	if err != nil {
		t.Fatal(err)
	}
	if len(got.Added) != 1 || got.Added[0].Title != "Collect swallows the read error" {
		t.Errorf("added %+v, want the hand file's finding alone", got.Added)
	}
}
